# Statistics in Machine Learning




# 1. Data Cleaning

### How Statistics is Used

Statistics such as mean, median, standard deviation, minimum, maximum and frequency counts help identify incorrect, inconsistent, duplicated or unusual values.

### Python Example


In [1]:
import pandas as pd
df=pd.DataFrame({"Age":[22,25,28,250,25],"Salary":[30000,35000,40000,45000,35000]})
print(df.describe())
print("Duplicates:",df.duplicated().sum())

              Age        Salary
count    5.000000      5.000000
mean    70.000000  37000.000000
std    100.645417   5700.877125
min     22.000000  30000.000000
25%     25.000000  35000.000000
50%     25.000000  35000.000000
75%     28.000000  40000.000000
max    250.000000  45000.000000
Duplicates: 1


### AI/ML Explanation

Statistical summaries help detect data-quality problems before model training so the model learns from cleaner and more reliable data.


# 2. Missing Value Handling

### How Statistics is Used

Mean, median and mode can be used for simple missing-value imputation. Median is often more robust than mean for skewed numerical data or data containing outliers.

### Python Example


In [3]:
import pandas as pd
import numpy as np
df=pd.DataFrame({"Salary":[30000,35000,np.nan,40000,100000]})
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
print(df)

     Salary
0   30000.0
1   35000.0
2   37500.0
3   40000.0
4  100000.0


### AI/ML Explanation

Statistical imputation helps algorithms work with incomplete datasets. Imputation values should be learned from training data to avoid data leakage.


# 3. Outlier Detection

### How Statistics is Used

Statistics helps identify unusual observations using methods such as IQR and Z-score.

$$IQR=Q_3-Q_1$$

Potential outliers are often checked outside:

$$Q_1-1.5(IQR)$$

and

$$Q_3+1.5(IQR)$$

Where $Q_1$ = first quartile, $Q_3$ = third quartile, and $IQR$ = interquartile range.

### Python Example


In [5]:
import numpy as np
data=np.array([10,12,13,14,15,16,18,50])
q1=np.percentile(data,25)
q3=np.percentile(data,75)
iqr=q3-q1
lower=q1-1.5*iqr
upper=q3+1.5*iqr
print("Potential Outliers:",data[(data<lower)|(data>upper)])

Potential Outliers: [50]


### AI/ML Explanation

Outliers can affect statistical estimates and some ML models. They should be investigated because they may represent errors or genuine rare observations.


# 4. Feature Engineering

### How Statistics is Used

Statistical relationships, distributions, aggregations and ratios can guide the creation of useful new features.

### Python Example


In [7]:
import pandas as pd
df=pd.DataFrame({"Total_Purchase":[1000,1500,2000],"Purchases":[5,6,8]})
df["Average_Purchase"]=df["Total_Purchase"]/df["Purchases"]
print(df)

   Total_Purchase  Purchases  Average_Purchase
0            1000          5             200.0
1            1500          6             250.0
2            2000          8             250.0


### AI/ML Explanation

Feature engineering uses knowledge of the data to create variables that may represent useful patterns more clearly for a model.


# 5. Feature Scaling

### How Statistics is Used

Statistics is used in standardization through the mean and standard deviation.

$$z=\frac{x-\mu}{\sigma}$$

Where $z$ = standardized value, $x$ = original value, $\mu$ = mean, and $\sigma$ = standard deviation.

### Python Example


In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df=pd.DataFrame({"Age":[20,30,40,50],"Salary":[25000,40000,60000,90000]})
scaled=StandardScaler().fit_transform(df)
print(scaled)

[[-1.34164079 -1.18143064]
 [-0.4472136  -0.56503205]
 [ 0.4472136   0.25683275]
 [ 1.34164079  1.48962994]]


### AI/ML Explanation

Scaling is useful for algorithms affected by feature magnitude, including KNN, SVM and PCA. Fit the scaler on training data only.


# 6. Data Normalization

### How Statistics is Used

Min-Max normalization uses the minimum and maximum to rescale data, commonly to 0–1.

$$x'=\frac{x-x_{min}}{x_{max}-x_{min}}$$

Where $x'$ = normalized value, $x$ = original value, $x_{min}$ = minimum and $x_{max}$ = maximum.

### Python Example


In [10]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df=pd.DataFrame({"Score":[20,40,60,80,100]})
df["Normalized"]=MinMaxScaler().fit_transform(df[["Score"]])
print(df)

   Score  Normalized
0     20        0.00
1     40        0.25
2     60        0.50
3     80        0.75
4    100        1.00


### AI/ML Explanation

Normalization places numerical features on a comparable bounded scale. Parameters should be learned from training data to avoid leakage.


# 7. Model Evaluation

### How Statistics is Used

Statistics provides metrics that summarize prediction quality. Regression commonly uses MAE, MSE and R², while classification commonly uses accuracy, precision, recall and F1-score.

### Python Example


In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
actual=[100,150,200,250]
predicted=[110,145,190,260]
print("MAE:",mean_absolute_error(actual,predicted))
print("MSE:",mean_squared_error(actual,predicted))
print("R2:",r2_score(actual,predicted))

MAE: 8.75
MSE: 81.25
R2: 0.974


### AI/ML Explanation

Evaluation metrics convert prediction performance into measurable values. The best metric depends on the problem and the consequences of different errors.


# 8. Linear Regression

### How Statistics is Used

Linear regression uses statistical relationships to model a continuous target.

$$\hat{y}=b_0+b_1x$$

Where $\hat{y}$ = predicted value, $b_0$ = intercept, $b_1$ = slope and $x$ = input feature.

### Python Example


In [15]:
import numpy as np
from sklearn.linear_model import LinearRegression
X=np.array([[1],[2],[3],[4],[5]])
y=np.array([40,50,60,70,80])
model=LinearRegression().fit(X,y)
print("Prediction:",model.predict([[6]])[0])
print("Slope:",model.coef_[0])

Prediction: 90.0
Slope: 10.000000000000002


### AI/ML Explanation

Linear regression estimates coefficients that describe associations between predictors and a continuous target under the model assumptions.


# 9. Logistic Regression

### How Statistics is Used

Logistic regression estimates class probability using the logistic function.

$$P(y=1|x)=\frac{1}{1+e^{-z}}$$

where $z=b_0+b_1x_1+\cdots+b_kx_k$.

$P(y=1|x)$ = probability of class 1, $b$ = coefficients and $x$ = features.

### Python Example


In [17]:
import numpy as np
from sklearn.linear_model import LogisticRegression
X=np.array([[1],[2],[3],[4],[5],[6]])
y=np.array([0,0,0,1,1,1])
model=LogisticRegression().fit(X,y)
print("Class:",model.predict([[4.5]])[0])
print("Probability:",model.predict_proba([[4.5]])[0])

Class: 1
Probability: [0.24585834 0.75414166]


### AI/ML Explanation

Logistic regression combines probability modeling with classification. A threshold converts the estimated probability into a class prediction.


# 10. Naive Bayes

### How Statistics is Used

Naive Bayes uses Bayes' theorem and assumes features are conditionally independent given the class.

$$P(C|X)=\frac{P(X|C)P(C)}{P(X)}$$

Where $P(C|X)$ = posterior, $P(X|C)$ = likelihood, $P(C)$ = prior and $P(X)$ = evidence.

### Python Example


In [19]:
from sklearn.naive_bayes import GaussianNB
X=[[1,20],[2,25],[3,30],[8,70],[9,80],[10,90]]
y=[0,0,0,1,1,1]
model=GaussianNB().fit(X,y)
print("Prediction:",model.predict([[7,65]])[0])
print("Probabilities:",model.predict_proba([[7,65]])[0])

Prediction: 1
Probabilities: [2.22657783e-27 1.00000000e+00]


### AI/ML Explanation

Naive Bayes calculates class probabilities from statistical patterns in training data and is commonly useful in classification tasks.


# 11. Clustering

### How Statistics is Used

Clustering groups similar observations without target labels. Distance measures are often used.

Euclidean distance:

$$d(x,y)=\sqrt{\sum_{i=1}^{n}(x_i-y_i)^2}$$

Where $d(x,y)$ = distance and $x_i,y_i$ = feature values.

### Python Example


In [21]:
import numpy as np
from sklearn.cluster import KMeans
X=np.array([[1,2],[1,3],[2,2],[8,8],[9,8],[8,9]])
model=KMeans(n_clusters=2,random_state=42,n_init=10)
labels=model.fit_predict(X)
print("Labels:",labels)
print("Centers:\n",model.cluster_centers_)

C:\Users\darshan\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\darshan\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\darshan\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darshan\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\darshan\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi

Labels: [0 0 0 1 1 1]
Centers:
 [[1.33333333 2.33333333]
 [8.33333333 8.33333333]]


C:\Users\darshan\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


### AI/ML Explanation

Statistics and distance measures help identify and describe groups of similar observations in unlabeled data.


# 12. Principal Component Analysis (PCA)

### How Statistics is Used

PCA uses variance and covariance to transform correlated numerical features into principal components that capture major directions of variation.

A covariance matrix can be written as:

$$\Sigma=\frac{1}{n-1}X_c^TX_c$$

Where $\Sigma$ = covariance matrix, $X_c$ = centered data and $n$ = number of observations.

### Python Example


In [23]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
X=np.array([[2,3,4],[3,5,6],[4,6,8],[5,8,10],[6,9,12]])
X_scaled=StandardScaler().fit_transform(X)
pca=PCA(n_components=2)
X_pca=pca.fit_transform(X_scaled)
print("PCA Data:\n",X_pca)
print("Explained Variance:",pca.explained_variance_ratio_)

PCA Data:
 [[-2.49810088 -0.07145641]
 [-1.14106246  0.11732837]
 [-0.05399399 -0.07652829]
 [ 1.30304443  0.11225649]
 [ 2.3901129  -0.08160016]]
Explained Variance: [0.99706742 0.00293258]


### AI/ML Explanation

PCA reduces dimensionality by keeping directions that explain large amounts of variance. Scaling is often important when features use different units.


# 13. Recommendation Systems

### How Statistics is Used

Statistics helps recommendation systems calculate averages, similarities and user-item relationships.

Cosine similarity:

$$\cos(\theta)=\frac{A\cdot B}{\|A\|\|B\|}$$

Where $A,B$ = user or item vectors and $\cos(\theta)$ = their cosine similarity.

### Python Example


In [25]:
from sklearn.metrics.pairwise import cosine_similarity
ratings=[
    [5,4,0,1],
    [4,5,0,1],
    [1,0,5,4]
]
similarity=cosine_similarity(ratings)
print("User Similarity Matrix:\n",similarity)

User Similarity Matrix:
 [[1.         0.97619048 0.21428571]
 [0.97619048 1.         0.19047619]
 [0.21428571 0.19047619 1.        ]]


### AI/ML Explanation

Recommendation systems use statistical patterns in interactions or ratings to estimate similarity and help generate personalized recommendations.
