# Statistics in Machine Learning


## 1. Data Cleaning

### Definition
Data cleaning is the process of identifying and correcting incorrect, duplicate, missing, or inconsistent data before training a machine learning model.

### Why We Need It
ML models learn from the data we provide. Clean data helps the model learn correct patterns and produce reliable predictions.

### Real-Life Example
Suppose an employee's age is entered as 250 instead of 25. Data cleaning helps identify such incorrect values.

### AI/ML Example
In a salary prediction dataset, we can check for missing values, duplicates, and unusual values before training.

### Explanation
Cleaning improves data quality and helps the ML model learn reliable patterns.


In [1]:
import pandas as pd
df = pd.DataFrame({"Age":[22,25,25,None,250],"Salary":[30000,40000,40000,45000,50000]})
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

Age       1
Salary    0
dtype: int64
Duplicates: 1


## 2. Missing Value Handling

### Definition
Missing value handling is the process of identifying and managing empty or unavailable values in a dataset.

### Why We Need It
Many ML algorithms cannot work properly with missing values, so we remove them or fill them using suitable values such as mean, median, or mode.

### Real-Life Example
If one student's mark is missing, we can fill it using the average mark of the class.

### AI/ML Example
In a student performance dataset, missing marks can be filled with the mean before training.

### Explanation
Handling missing values gives the model complete and usable input data.


In [3]:
import pandas as pd
import numpy as np
df = pd.DataFrame({"Marks":[65,72,np.nan,80,75]})
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df)

   Marks
0   65.0
1   72.0
2   73.0
3   80.0
4   75.0


## 3. Outlier Detection

### Definition
Outlier detection identifies values that are unusually far from other values in a dataset.

### Why We Need It
Outliers can affect statistical calculations and reduce the performance of models that are sensitive to extreme values.

### Real-Life Example
If most salaries are between 30,000 and 60,000 but one is 5,00,000, it may be an outlier.

### AI/ML Example
The IQR method can detect unusually high or low values before training a salary prediction model.

### Explanation
Detecting outliers helps us decide whether unusual values should be kept, corrected, transformed, or removed.


In [5]:
import numpy as np
data = [18,20,22,24,25,27,95]
Q1 = np.percentile(data,25)
Q3 = np.percentile(data,75)
IQR = Q3-Q1
lower = Q1-1.5*IQR
upper = Q3+1.5*IQR
outliers = [x for x in data if x < lower or x > upper]
print("Outliers:", outliers)

Outliers: [95]


## 4. Feature Engineering

### Definition
Feature engineering is the process of creating or transforming input features to provide more useful information to a machine learning model.

### Why We Need It
Better features can make useful patterns easier for the model to learn and improve performance.

### Real-Life Example
From a person's date of birth, we can create a new feature called Age.

### AI/ML Example
For student performance prediction, Math and Science marks can be combined into an Average Marks feature.

### Explanation
The new feature summarizes useful information that may help the model make better predictions.


In [7]:
import pandas as pd
df = pd.DataFrame({"Math":[68,78,88],"Science":[72,82,92]})
df["Average_Marks"] = df[["Math","Science"]].mean(axis=1)
print(df)

   Math  Science  Average_Marks
0    68       72           70.0
1    78       82           80.0
2    88       92           90.0


## 5. Feature Scaling

### Definition
Feature scaling transforms numerical features so that they are on comparable scales.

### Why We Need It
Large-valued features can dominate smaller-valued features in distance-based or gradient-based algorithms.

### Real-Life Example
Age may range from 20 to 60 while Salary ranges from 30,000 to 1,00,000, so scaling puts them on comparable scales.

### AI/ML Example
StandardScaler can standardize Age and Salary before using them in models such as Logistic Regression, SVM, or K-Means.

### Explanation
Standardization uses mean and standard deviation, producing features with mean approximately 0 and standard deviation approximately 1.


In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
X = pd.DataFrame({"Age":[22,32,42],"Salary":[35000,55000,75000]})
scaled = StandardScaler().fit_transform(X)
print(scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


## 6. Data Normalization

### Definition
Data normalization rescales numerical values to a common range, commonly from 0 to 1.

### Why We Need It
It is useful when features have different ranges and feature magnitude matters to the algorithm.

### Real-Life Example
If product prices range from 100 to 10,000, normalization can convert them into values between 0 and 1.

### AI/ML Example
MinMaxScaler can normalize input features before using them in scale-sensitive ML algorithms.

### Explanation
Normalization preserves the ordering of values while converting them to a common range.


In [11]:
from sklearn.preprocessing import MinMaxScaler
data = [[10],[30],[50],[70]]
normalized = MinMaxScaler().fit_transform(data)
print(normalized)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


## 7. Model Evaluation

### Definition
Model evaluation measures how well a trained machine learning model performs on unseen or test data.

### Why We Need It
It helps us understand prediction quality and compare different models.

### Real-Life Example
We can compare predicted student scores with actual scores to check prediction quality.

### AI/ML Example
For regression, MAE, MSE, and R² can compare predicted values with actual values.

### Explanation
These statistical metrics quantify prediction error and how well the model explains variation in the target.


In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
actual = [45,55,65,75]
predicted = [47,53,66,73]
print("MAE:", mean_absolute_error(actual,predicted))
print("MSE:", mean_squared_error(actual,predicted))
print("R2:", r2_score(actual,predicted))

MAE: 1.75
MSE: 3.25
R2: 0.974


## 8. Linear Regression

### Definition
Linear Regression models the relationship between input variables and a continuous target variable.

### Why We Need It
We use it to predict numerical values such as salary, price, marks, or sales.

### Real-Life Example
A company can estimate salary based on years of experience.

### AI/ML Example
A Linear Regression model can learn the relationship between experience and salary and predict a new employee's salary.

### Explanation
The model fits a line that minimizes prediction errors and uses the learned relationship to estimate continuous values.


In [15]:
import pandas as pd
from sklearn.linear_model import LinearRegression
X = pd.DataFrame({"Experience":[1,2,3,4,5]})
y = [28000,33000,38000,43000,48000]
model = LinearRegression()
model.fit(X,y)
new_data = pd.DataFrame({"Experience":[6]})
print("Predicted Salary:", model.predict(new_data)[0])

Predicted Salary: 53000.0


## 9. Logistic Regression

### Definition
Logistic Regression is a classification algorithm that estimates the probability of a class using a logistic function.

### Why We Need It
We use it for categorical targets, especially binary outcomes such as Yes/No, Pass/Fail, or 0/1.

### Real-Life Example
A bank can predict whether a customer will repay a loan or not.

### AI/ML Example
A model can use study hours to estimate whether a student will pass or fail.

### Explanation
The model produces probabilities and applies a decision threshold to assign the final class.


In [17]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
X = pd.DataFrame({"Hours":[1,2,3,4,5,6]})
y = [0,0,0,1,1,1]
model = LogisticRegression()
model.fit(X,y)
new_data = pd.DataFrame({"Hours":[5]})
print("Prediction:", model.predict(new_data)[0])
print("Probability:", model.predict_proba(new_data))

Prediction: 1
Probability: [[0.15694029 0.84305971]]


## 10. Naive Bayes

### Definition
Naive Bayes is a probabilistic classification algorithm based on Bayes' Theorem and an assumption of conditional feature independence.

### Why We Need It
It is useful for fast classification tasks such as spam detection, text classification, and sentiment analysis.

### Real-Life Example
An email service can classify a message as spam or not spam based on words in the email.

### AI/ML Example
Naive Bayes calculates class probabilities from feature values and predicts the class with the highest posterior probability.

### Explanation
Statistics is central because the algorithm learns class probabilities and feature likelihoods from training data.


In [19]:
from sklearn.naive_bayes import GaussianNB
X = [[18,1],[22,1],[35,0],[40,0]]
y = [0,0,1,1]
model = GaussianNB()
model.fit(X,y)
print("Prediction:", model.predict([[38,0]])[0])

Prediction: 1


## 11. Clustering

### Definition
Clustering is an unsupervised learning technique that groups similar data points without predefined class labels.

### Why We Need It
We use it to discover hidden groups or patterns in unlabeled data.

### Real-Life Example
A shopping company can group customers based on spending habits.

### AI/ML Example
K-Means can group customers based on features such as income and spending score.

### Explanation
K-Means uses distances and cluster centers to assign similar observations to the same group.


In [21]:
import numpy as np
from sklearn.cluster import KMeans
X = np.array([[2,3],[3,4],[4,3],[12,13],[13,12],[14,13]])
model = KMeans(n_clusters=2,random_state=42,n_init=10)
labels = model.fit_predict(X)
print("Cluster Labels:", labels)
print("Cluster Centers:\n", model.cluster_centers_)

Cluster Labels: [0 0 0 1 1 1]
Cluster Centers:
 [[ 3.          3.33333333]
 [13.         12.66666667]]


C:\Users\darshan\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\darshan\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\darshan\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darshan\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\darshan\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi

## 12. Principal Component Analysis (PCA)

### Definition
PCA is a dimensionality reduction technique that transforms correlated features into fewer uncorrelated principal components.

### Why We Need It
We use PCA to reduce the number of features while preserving as much important variation as possible.

### Real-Life Example
Many similar measurements can be summarized into fewer measurements that retain most of their information.

### AI/ML Example
In a dataset with many correlated features, PCA can reduce the feature count before model training.

### Explanation
PCA uses variance and covariance to find directions that capture the greatest variation in the dataset.


In [23]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
X = np.array([[2,5,8],[3,7,10],[5,9,13],[7,12,16],[9,14,19]])
X_scaled = StandardScaler().fit_transform(X)
X_pca = PCA(n_components=2).fit_transform(X_scaled)
print(X_pca)

[[-2.25636491 -0.06718501]
 [-1.38611803  0.08603068]
 [-0.14494597 -0.04000675]
 [ 1.27312842  0.07359925]
 [ 2.51430049 -0.05243818]]


## 13. Recommendation System

### Definition
A recommendation system predicts or ranks items that a user may prefer based on ratings, interactions, similarities, or behavior patterns.

### Why We Need It
We use recommendation systems to personalize products, movies, music, videos, or other content.

### Real-Life Example
A movie platform can recommend movies similar to those a user previously rated highly.

### AI/ML Example
Statistics can summarize ratings and measure similarities between users or items to help generate recommendations.

### Explanation
Average ratings provide a simple statistical signal, while advanced systems use similarity measures and learned user-item patterns.


In [25]:
import pandas as pd
ratings = pd.DataFrame({"Movie":["A","B","C","D","E"],"Rating":[5,4,3,5,4]})
print("Average Rating:", ratings["Rating"].mean())

Average Rating: 4.2
